# Generated by Django 4.2 on 2025-01-30 11:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "title2",
                    models.CharField(max_length=155, verbose_name="Заголовка 2"),
                ),
                ("imgae", models.ImageField(upload_to="banner/", verbose_name="Фото")),
                ("video", models.URLField(verbose_name="Ссылка на видео")),
            ],
            options={
                "verbose_name_plural": "Настройка Баннера в Главной Страницы",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("Locations", "Locations"),
                            ("phone", "phone"),
                            ("email", "email"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="ContactFrom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155)),
                ("email", models.EmailField(max_length=254)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Обраная связ",
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_game",
                    models.CharField(max_length=155, verbose_name="Заголовка Игры"),
                ),
                (
                    "descriptions_game",
                    ckeditor.fields.RichTextField(verbose_name="Описание игры"),
                ),
                (
                    "title_match",
                    models.CharField(max_length=155, verbose_name="Заголовка Мачт"),
                ),
                (
                    "description_match",
                    ckeditor.fields.RichTextField(verbose_name="Описание Матч"),
                ),
                (
                    "title_team",
                    models.CharField(max_length=155, verbose_name="Заголовка  Команды"),
                ),
                (
                    "description_team",
                    ckeditor.fields.RichTextField(verbose_name="Описание  Команды"),
                ),
                (
                    "title_news",
                    models.CharField(max_length=155, verbose_name="Заголовка  Новости"),
                ),
                (
                    "description_news",
                    ckeditor.fields.RichTextField(verbose_name="Описание  Новости"),
                ),
            ],
            options={
                "verbose_name_plural": "Настройка Главной Страницы",
            },
        ),
    ]
