# Generated by Django 4.2 on 2025-01-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactfrom",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
