# Generated by Django 4.2 on 2025-02-03 10:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_contactfrom_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactfrom",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="news", verbose_name="Фото"
            ),
        ),
        migrations.AddField(
            model_name="contactfrom",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="news", verbose_name="Фото 2"
            ),
        ),
        migrations.AddField(
            model_name="contactfrom",
            name="text",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Текст"
            ),
        ),
    ]
